version: '3'

services:
  fbdatools:
    image: bplein/fbdatools:latest
    container_name: fbdatools
    hostname: fbdatools
    restart: always
    ports:
        - "${SSH_PORT}:${SSH_PORT}/tcp"
    volumes:
      - $HOME:/root
      - mnt1:/mnt/mnt1
      - mnt2:/mnt/mnt2
volumes:
  mnt1:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_MOUNT},nolock,soft,rw"
      device: ":/volume2/dockertest/mnt1"
  mnt2:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_MOUNT},nolock,soft,rw"
      device: ":/volume2/dockertest/mnt2"
    