version: '3'

services:
  fbdatools:
    image: bplein/fbdatools:latest
    container_name: fbdatools
    hostname: fbdatools
    restart: always
    ports:
        - "${SSH_PORT}:${SSH_PORT}/tcp"
    volumes:
      - ./tools:/home/$USER/tools
      - mnt1:/mnt/mnt1
volumes:
  mnt1:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nolock,soft,rw,local_lock=none"
      device: ":/${NFS_EXPORT}"
    